# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        '/:year/:month/:title.html'
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:  pretty
# relative_permalinks: true //deprecated

# Setup
title:  'Erick Ndava'
tagline:  'Spatial Data Science'
description:  'A geospatial scientist. Here I blog on things geo and data, the rumblings of an enthusiast.'
url:  'https://erickndava.github.io/'
images:       '/images/'


# About/contact
author:
  name:           'Erick Ndava'
  email:          'erick.ndava@gmail.com'
  url:            'https://erickndava.github.io'
  twitter_handle: '@erickndava'
  twitter:        'https://twitter.com/erickndava'
  github:         'https://github.com/erickndava'
  linkedin:       'https://linkedin.com/in/erick-ndava-89670716'
  


# Custom vars
# version:             2.1.0

# plugins: [jekyll-paginate] **commented out 09/06/2025
 
url: "https://erickndava.github.io" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
  - jekyll-paginate # added in on 09/06/2025

paginate:         5
paginate_path:    "page:num"
