# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:  pretty
# relative_permalinks: true //deprecated

# Setup
title:  Erick Ndava
tagline:  'A spatial doodle'
description:  'A geospatial scientist. Here I blog on things geo and data, the rumblings of an enthusiast.'
baseurl:  ""
url:  ""
paginate: 5

# About/contact
author:
  name: Erick Ndava
  url:  https://twitter.com/erickndava
  email:  erick.ndava@gmail.com

# Custom vars
version:             2.1.0

