# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:  pretty
# relative_permalinks: true //deprecated

# Setup
title:  neaRThings
tagline:  'A spatial doodle'
description:  'neaRThings is a blog on things geo and data, the rumblings of an enthusiast.'
baseurl:  ""
url:  ""

# url:  "https://erickndava.github.io"
# baseurl:  ""
paginate: 1

# About/contact
author:
  name: Erick Ndava
  url:  https://twitter.com/erickndava
  email:  erick.ndava@gmail.com

# Custom vars
version:             1.0.0
